

title: "Mohammad Faezi"
description: "AI Researcher & Software Engineer"
url: "https://m-faezi.github.io"
baseurl: ""

theme: jekyll-theme-minimal

plugins:
  - jekyll-feed
  - jekyll-seo-tag

markdown: GFM
highlighter: rouge

author: "Mohammad Faezi"
x_username: "farshad_faezi"
github_username: "m-faezi"
linkedin_username: "mohammad-faezi"
google_scholar_user: "V4iE8TIAAAAJ"

avatar: "assets/images/avatar.jpg"

resume_download_url: "https://drive.google.com/file/d/1jOSrCVVE8vcs3jlMj5HOViVA8-HftfVI/view?usp=drive_link"

show_downloads: false
google_analytics: false

exclude:
  - node_modules
  - Gemfile
  - Gemfile.lock
  - vendor


